# Project Excellence and Professionalism

## Overview {-}

Welcome to MCOM 221! You are about to embark on a creative adventure. The specific goal of this journey is to create attention-grabbing  and alluring short films. However, the general goal is far more valuable as you learn things about yourself you never knew. This course will equip you with the knowledge to develop transferable life skills that will help you in your career and professional life after you complete your education.

In addition, there is a larger element of this course that connects us to people from the past, present, and future. Namely, storytelling.

According to communications theorist Walter Fischer, human beings are more than *Homo sapiens*, we are Homo *narrans*, man the storyteller. Storytelling is hardwired into our brains and our cultures and history. Stories are how we make sense of our life and our world. This is why religion, philosophy, literature, and myth have been vital to human culture and understanding. Even science is a story—it tells us how the world works. But it cannot tell us why. Only story-based meaning can reveal why life is important, how we should live our lives, and why there is something rather than nothing. Think of the Bible. If one were to take out the stories, it would be a thin book.

Don’t let these ideas scare you. This is a creative course not a philosophic one. The point here is that as you increase your storytelling skills—a vital part of this course—you will join the community of narrators throughout human history who have shared their wisdom, insight, and understanding. This knowledge serves as the foundation for building identities, developing traditions, and discovering the types of meaning that make life worth living across all cultures.

This course will focus on one aspect of narratives, namely visual storytelling. How do we use pictures (and sounds) to create meaning and emotionally connect people to ourselves and each other? This will be the deeper theme operating beneath the surface of this course. (In film terms it will be the subtext beneath the text.)

In practical terms, the better you are at communicating stories (relative to each profession), the better you will be at your job. Fasten your seat belt, you are about to find out why we have focused on the above to start this course.

### Topics {-}

This unit is divided into the following topics:

1. Course Introduction  
1. Excellence and Professional and Personal Development  
1. 15 Tips for Doing Your Best  
1. Transferable Skills  

### Learning Outcomes {-}

When you have completed this unit, you should be able to:

  - Describe excellence and why it is important  
  - Define what constitutes an excellent film project  
  - Articulate the big picture of why stories and creativity are important  
  - Determine potential transferable life skills  
  - Self-assess your strengths and weaknesses  
  - Plan what you want to focus on during the course in terms of your professional and personal growth.  

### Activity Checklist {-}

```{block2, type='reflect'}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

 <!-- [plugin:content-inject](_schedule) -->

- Write your first two Film Journal entries for this unit.  
- Choose a glossary and start learning 5 new film terms a day.  
- Read the Introduction which sets up the course ahead and Chapter One “Project Excellence and Professionalism” in the course textbook.  
- Reflect on the 15 Tips for Doing Your Best.  
- Reflection on the transferable life skills presented.  

**Assessment**

- Film Journal

```

### Resources {-}

Here are the resources you will need to complete this unit.

  - Introduction and Chapter One of the course text: *Digital Filmmaking: A Beginner’s Guide to Mastering the Craft*, by Ned Vankevich (e-text)  
  - [How to Start a Creative Journal](https://karenbanes.com/how-to-start-a-creative-journal) (Be sure to click on the internal links on this website)  
  - [How to Journal Every Day for Increased Productivity, Clarity, and Mental Health](https://www.youtube.com/watch?v=hUTWo7_W0lc)  
  - [How To Grow Professionally](https://brandyourself.com/blog/guide/how-to-grow-professionally/)  
  - [Creative blocks website](https://www.goodtherapy.org/learn-about-therapy/issues/creative-blocks)  
  - Other resources will be provided in the unit.  

## Course Introduction

We begin Unit 1 marvelling at the magic of film and cinema. (Read the course text Preface.) The ability of visually-centered storytelling to cross cultures and to captivate, educate, and entertain audiences is a universal contemporary phenomenon. For instance, how a series of flickering lights and images projected at 24, 25, and 30 frames a second can create emotions and experiences we all share is a wondrous mystery.

Less mysterious is how this is done. There are techniques, rules, guidelines, and practices that can help us reach people in the ways that films, TV shows, streaming Internet programs, news, and the host of other visually-centered can make us laugh, cry, and emotionally move and engage us. The worst thing that can be said by an audience is that “I want my five, ten, sixty, or ninety minutes back (depending on the length of what we have viewed). Learning the methods to avoid this and to engage our audience will be central to this course.

**WHAT LIES AHEAD**

This course will be divided up into ten segments or units. Each segment (or chapter) is self-contained but each section is inter-connected and vital for the others. A word to the wise—do note not skip a section, even if you think that you already know it. Each section of the course will build upon the previous one.

See the overview of the course and the ten units in the Introduction to the course text: *Introduction to Digital Filmmaking: A Beginner’s Guide to Mastering the Craft*. 

Of special note, Unit Ten and Chapter Ten will be a summary and a celebration of what you have learned during the course. It will also be a time for awards to be handed out for outstanding and excellent work such as Awards for Best film, Best Director, Best Cinematography, Best Editing., Best Story, and Most Imaginative and Most Improved Filmmaker, etc. This is noted here to give you a goal to work towards: namely, to win one of the top awards.

As can be gleaned from the above, this course will start with the most basic elements and proceed to creating a short film with a strong beginning, middle, and end. As you move through the course keep the mindset that this will be a fun, enjoyable, and exciting adventure.

### Learning Activities {-}

 <!-- [plugin:content-inject](../_1-1) -->

```{block2, type='reflect'}

#### The Importance of the Film Journal {-}

During this course you are encouraged to keep a “Film Journal.” This is important for many reasons, including helping you to brainstorm ideas, as well as ponder and process what you are learning. The journal will also help you to keep a record of your course activities, and note feedback of what does and does not work in film projects of your fellow course members. In addition, some of the exercises for this course will not be graded (for reasons that will be explained ahead) but this does not mean you will not be accountable for doing them. Your journal will be submitted at the end of the course and will play a role in the grade you receive. In short, students who engage with the course well will in general receive higher marks.

Also, note that you may be asked to use your journal entries to participate in discussions, presentations, and other learning activities in the FAR Centre Facilitated Learning Labs. Please check with your facilitator about specific due dates for activities, including journal responses.


#### Film Journal Entry: {-}

Based on the importance of the course journal make your first two entries for this unit:

- **Entry One:** After reading the course text Introduction, describe your best take-aways of what you have learned.
- **Entry Two:** Study the recommended how-to-write-a-journal resources and log what you learned from them and how it will help you during the course.
  - [How to Start a Creative Journal](https://karenbanes.com/how-to-start-a-creative-journal) (Be sure to click on the internal links on this website)  
  - [How to Journal Every Day for Increased Productivity, Clarity, and Mental Health](https://www.youtube.com/watch?v=hUTWo7_W0lc)  

```

```{block2, type='caution'}

**NOTE** : your journal entries do not have to be long but they should be detailed and specific enough to indicate that you have engaged the course material and projects.

```

### Learning Activities {-}

<!-- [plugin:content-inject](../_1-2) -->

```{block2, type='reflect'}

#### Film Terms and Vocabulary Needed for this Course {-}

The course text Introduction also draws attention to the fact that you will learn many new terms and concepts during this course and that it is important for you to find resources that you can consult throughout the course to re-enforce their meaning and application to the course. Several websites will be cited here such as:

  - <a href="https://www.studiobinder.com/blog/movie-film-terms/#p"> studiobinder movie film terms </a>  
  - A more comprehensive glossary can be found at <a href="https://en.wikipedia.org/wiki/Glossary_of_motion_picture_terms"> Wikipedia’s Glossary of Motion Picture terms </a> ;  
  - and <a href="https://www.filmsite.org/filmterms.html"> AMC Film Terms Glossary </a>  

Commit to learning ***5*** new film terms each day by starting with A and going to Z. The more you focus on this the better you will do in the course. Don’t worry if you do not understand a term. We will be covering many of them during the course. The important thing is to become familiar with important film terms and vocabulary.

#### Questions to Consider {-}

After completing the activities above, consider the following questions:

- Why is this course important to you?  
- What do you hope to learn and how can it aid your future?  

```

```{block2, type='caution'}

**Note** that while the above learning activity is ungraded, it is designed to help you succeed in your assessments in this course.

```

## Excellence and Professional and Personal Development

This course will focus on the classical approach to filmmaking, that is, making motivated film stories and executing them in ways that help audiences to fully engage the story and characters without unnecessary distractions. In doing so, the course has a lofty goal: to aim for excellence. Excellence means a high standard of being good. This is of course relative to being an Introductory course with students who are just beginning their filmmaking journey, or are taking this course as an elective. But like any course, if you shoot for an A you will do better than settling for average and mediocrity.

Excellence is important in filmmaking because our competition is great. Film is a public medium. It is designed to be shown to audiences and the quality of our projects, like many things we do in life, will be judged whether we want them to be or not.

One of the transferable life skills of this course is to help us be more professional. Thus the more we shoot for excellence, the more we will develop abilities that will serve us better in our careers ahead.

At the same time we must not confuse excellence with perfection. Our beginning films and projects will have lots of mistakes and things that do not work. This should not deter us from our goal of excellence. All great artists, athletes, business leaders, and a host of other professional make mistakes. The key is to learn from them and to keep improving our craft.

HELPFUL HINT: For insight into how great artists, athletes, and performers use mistakes to grow in their art and craft see the following book by Daniel Coyle: [THE TALENT CODE: GREATNESS ISN’T BORN. IT’S GROWN. HERE’S HOW](http://danielcoyle.com/the-talent-code/).

Our goal then is to learn how to seek to produce visually-driven, digital film stories that are technically and artistically proficient, meaningfully engaging, motivated, and fraught with excellence.

As you can see excellence and professionalism go hand in hand. In order to grow and excel in a craft we need to grow and excel at being professional. Implied here is that we also need to mature and grow personally as we develop the character traits necessary for being a mature, moral, and responsible person.

### Learning Activities {-}

 <!-- [plugin:content-inject](../_1-3) -->

```{block2, type='reflect'}

#### Read and Reflect {-}

Read Chapter One “Project Excellence and Professionalism” in the course textbook.

As you study and ponder what excellence and what professional and personal development mean, log in your journal why they are important and how you hope to focus on them during the course. Which character traits are your strongest and which do you need to work on? How will you do this? To help you with these entries study this resource:

[How To Grow Professionally](https://brandyourself.com/blog/guide/how-to-grow-professionally/)

```

## 15 Tips for Doing Your Best

The following will help you to not just do well in this Film project, but will make it fun and more enjoyable and hopefully be one of your favourite courses ever:

1. ***Keep your eye on the prize.*** Creating an excellent project and growing as a professional and better person through the process.  

2. ***Meeting Deadlines.*** Being on time is vital in any profession, especially in filmmaking where the cost of feature film shoots can be thousands of dollars per hour. Plan your time and schedule accordingly so that you make your due date. Failure to do so will result in reduced marks on your assignment.  

3. ***Avoiding Distractions.*** In our Internet-cell phone era we are inundated and surrounded by 24/7 distractions. If we succumb to them we will not meet our deadlines and thus delay our professional and personal development. Learning to discern what is vital and what is the tyranny of the unimportant and unnecessary urgent is a critical skill to develop today. Focus on it and you will go further in the course. (**Tip:** *turn off all notifications on your cell phone. In fact, turn off or put your cell phone away while you are working on your Film course. You will find that this will help you to focus on and finish your assignments quicker and with more creativity*).

4. ***Focussing on the positive***. Most of the assignments ahead will be challenging. Cultivate a “can do attitude.” For context think about your taking a piano lesson course. You would not expect to sit down and immediately play chords and songs. You would have to learn to play the notes, then chords, then songs over a period of time. Filmmaking is similar. There are notes to learn (film shots), chords to learn (film scenes), before we can create melodies (film sequences) and songs (full films).  

5. ***It takes time and practice to master film***. If you find you have time, or if you are truly interested in learning the world of film or becoming a filmmaker, I encourage you to go beyond the course exercises. For example, continue to find and shoot interesting visual compositions (they are all around you) during the course, or practice fascinating and more complicated motion shots and two and three person shots. The more you do this the faster you will grow in your craft. Think about musicians. They practice over and over everyday.  

6. ***Study the practical tips and helpful hints in these units***. Pay attention to them. They will help fast-track your skills growth.  

7. ***Find and do what you love***. During this course you will discover things you love to do and those that you do not. As a filmmaker, every skill set is vital for the final production – but you will discover which roles you are better at and enjoy the most. Even if you do not go into filmmaking as a career this self-insight will be invaluable as you make life decisions ahead.  

8. ***Make a firm commitment to succeed***. When we are double-minded or not sure of what we want, we will waiver and fall prey to distraction and self-sabotage. Resolve not to give up as you make your projects despite what “Murphy’s Law” tosses your way. (*To be covered later.*)

9. ***Strive for balance***. The emphasis on excellence and professional and personal development must not make us “lose our soul.” Too many people get caught up in goals and ambition and end up failing in their marriage and relationships. Remember we are physical, mental, spiritual, emotional, and relational beings and must find a balance that lets us grow in each part equally. This is the key to personal flourishing.  

10. ***Create strong and healthy relationships***. During this course you will discover a lot about yourself and others. Some people will be easy to work with and some won’t. Some will be diligent and some won't. Choose your teammates wisely and if you have a winning rapport with them, you might want to work with them on the next project. One of the keys to success in the professional world is cultivating strong and fruitful relationships. Start the process here.  

11. ***Follow your intuition***. If you’ve never experimented with following your deeper instincts or “gut feelings” try it during this course. Often this will take you to new creative places. It might not always work but you will learn a lot from doing so.  

12. ***Take risks***. We don’t grow unless we try new things and fail. They key is not to get discouraged but to shake off a loss and fight to win again.  

13. ***Practice, practice, practice. Learn, learn, learn***. Your best competition is continually practicing and learning their craft. So should you. You need to cultivate both a strong work ethic and a smart ethic. Take the time to think things through before launching into something.  

14. ***Take responsibility for yourself and your future***. Playing the blame game or the victim or continually making excuses will not get you ahead in life.  

15. ***Find inspiring quotes and pin them to your computer or wall***. Most of us need encouragement especially when the going gets tough. Seek out inspiration that helps keep you going. The following strike some of the themes of this course:

- *"Success is not final; failure is not fatal: It is the courage to continue that counts."* - Winston S. Churchill  

- *"It is better to fail in originality than to succeed in imitation."* - Herman Melville  

- *"You will become clever through your mistakes."* - German Proverb in "The Talent Code"  


### Learning Activities {-}

 <!-- [plugin:content-inject](../_1-4) -->

```{block2, type='reflect'}

#### Reflection {-}

Which of the tips in this section appeal to you most? Which do you need to focus on during the course? Write your response in your journal and share with your facilitator and/or classmates which are most important and why. Find an inspiring quote and share it with your peers.

```

## Transferable Skills

This class is about more than making films. If followed diligently, you will learn a lot about yourself, others, and the world around you. You will also learn skills and traits that will play an important role in your life journey ahead. Some of the transferable skills can include:

  - Growing in your creative skills  
  - Growing in your teamwork skills  
  - Growing in your critiquing skills  
  - Growing in your ability to overcome obstacles  
  - Meeting deadlines and taking responsibility  
  - Becoming a leader  
  - Learning to take constructive criticism  
  - Committing to continual learning and improvement  
  - Developing a positive, can-do attitude  
  - Crafting what you want to say and communicating it well  
  - Learning the power of story and how it impacts many areas in our lives.  


### Learning Activities {-}

 <!-- [plugin:content-inject](../_1-5) -->

```{block2, type='reflect'}

#### Reflection on Life Skills {-}

Which of the life skills above are important to you and why? Log this in your journal. Which life skill(s) can you add to the list? Share your responses with your Facilitator and classmates.

```

```{block2, type='caution'}

**NOTE**: Be sure to revisit these journal entries on Tips to Do Well and Transferable Life Skills as you monitor your progress during the course. One of the actives in Unit Ten will involve your writing a summary of the best lessons you learned from the course and about yourself. Again, this is a reminder of how important our course journal will be. 

```

## Summary {-}

In this first unit, you have had the opportunity to learn about what this course entails, why it is important, and the role that professional and personal development will play. You also had a chance to respond to tips of how to make the most of this course and what skills you can transfer from it to your life.

## Assessment {-}

<!-- [plugin:content-inject](../../assignments/_film-journal)-->

```{block2, type='assessment'}

### Film Journal {-}

After completing this unit, including the learning activities, you are asked to make sure you are doing journal entries and when appropriate to share your responses with your facilitator and classmates when you meet.

Note that entries are expected for every unit.  Your journal reflections are submitted at the end of the course as part of the Final Exam: Self Assessment worth 30% of your course grade.


#### Grading Criteria: {-}

See the Assessments section for more details on submitting your journal, as well as the grading criteria.

```

## Checking your Learning {-}

```{block2, type='progress'}

Before you move on to the next unit, you may want to check to make sure that you are able to:

  - Describe excellence and why it is important.  
  - Define what constitutes an excellent film project.  
  - Articulate the big picture of why stories and creativity are important.  
  - Determine potential transferable life skills.  
  - Self-assessing your strengths and weaknesses.  
  - Plan what you want to focus on during the course in terms of professional and personal growth.  

```

