# Visual Composition

## Overview {.unnumbered}

We will now make our theory more practical. So far, we have focused on project excellence and the three phases of filmmaking we will use to create it. In this unit we will concentrate on where it all begins visually – the single image and how to craft it well.

This unit will also give you a chance to apply what you are learning in a creative way. Don’t worry if you think you are not creative or artistic We will focus on simple elements and reveal how they can help you see the world and capture it in exciting ways. We will do so by focusing on composition—the way in which the elements in a picture or image are arranged.

Visual composition will play an important role in this course, so taking the time to learn it is well worth the investment.

### Topics {.unnumbered}

This unit is divided into the following topics:

1. Elements of Composition
1. Principles of Composition
1. Photographic Themes

### Learning Outcomes {.unnumbered}

When you have completed this unit, you should be able to:

- Describe the elements used in visual compositions
- Define composition principles
- Study the works of noted photographers and apply composition elements and principles to photographs you create
- Create photos that reveal your understanding of the chapter’s content

### Learning Activities {.unnumbered}

Here is a list of learning activities that will benefit you in completing this unit. You may find it useful for planning your work.

::: {.learning-activity}

- Read and study Chapter 3 of course e-text: *Digital Filmmaking: A Beginner’s Guide to Mastering the Craft.*
- Read the article “11 Thoughts: An Introduction to Photographic Composition” by Todd Vorenkamp and reflect on the question provided.
- Read the article “20 Composition Techniques That Will Improve Your Photos”, and practice and apply techniques and principles of design.
- Review the suggested websites to enrich your understanding of photographic themes and find images that stand out in intriguing, startling, fascinating, and emotionally moving ways.

*Note*: Working through course activities will help you to meet the learning outcomes and successfully complete your assessments.

:::

<!-- ### Assessment {.unnumbered}

**Course Journal**

After completing this unit, including the learning activities, you are asked to make sure you are doing journal entries and when appropriate to share your responses with your facilitator and classmates when you meet.

Note that entries are expected after every unit. Your journal reflections are submitted at the end of the course as part of the Journal One: Personal Journal and self assessment.

**Assignment 2: Composition Exercise**

*This activity is ungraded, but part of journal entry*

After you have done some composition research and explored great photographers and photos and their compositional techniques and aesthetics, review Chapter 3 and go out and find and create five outstanding visual compositions with your camera (cell phone, DSLR, etc.). Share these with your family, friends, and peers and get their feedback about what worked and did not work. When you have found your best images upload them to the course online folder where the class assignments will be stored.

Remember, the name of the game is to learn not to be perfect.

::: {.note icon="true"}
Please see the Assessment section in Moodle for assignment details as well as the grading criteria.
::: -->

### Assessment {.unnumbered} 

Please see the Assessment section in Moodle for assignment details.

### Resources {.unnumbered}

Here are the resources you will need to complete this unit.

- Chapter Three of course text: *Digital Filmmaking: A Beginner’s Guide to Mastering the Craft*, by Ned Vankevich [-@VankevichDigitalFilmmaking] (e-text)
- The Visual Elements: The Building Blocks of Composition in Art
- 20 Composition Techniques That Will Improve Your Photos
- Taking Constructive Criticism Like a Champ
- How Criticism triggers Growth…
- Principles of Design
- Guidelines for Visual Composition Assignment
- Other resources will be provided in the unit.

## Elements of Composition

At heart, visual composition means the intentional arrangement or conscious activity of constructing the “ingredients” of an image. As we grow in our filmmaking craft, we must continually be aware of what takes place within the frame (the border of a picture or a film shot). Focusing on a single image can help train us to do this.

::: {.note icon="true"}

**Important Tip**: Before continuing below, study this overview of the building blocks of composition in art: [The Visual Elements: The Building Blocks of Composition in Art](http://www.artyfactory.com/art_appreciation/visual-elements/visual-elements.html){target="_blank"}

:::

The following are some of the formal elements that make up the design and structure of an image. However, it is important to remember that subject matter and composition are linked and therefore do not get locked in to rigidly adhering to what you are learning. Many masters break the rules but they know them well before they do so.

- Line
- Shape (geometric, organic, natural)
- Colour (hues, intensities, symbolism)
- Texture (tactile feel)
- Value (shadows and shading)
- Form (3-D, 2-D)
- Space (positive/objects); (negative/space between objects)
- Depth (foreground/mid-ground/background)

## Principles of Composition

In addition to elements of design, there are also principles or general rules that help give structure to visual compositions and which can also lend meaning or a theme to an image. Elements are specific things whereas principles are more general. Here are four that the course text focuses on:

**1. Balance**

**2. Rule of Thirds**

**3. Repetition and Patterns**

**4. Combinations**

There are many other principles such as the use of triangles and frame within a frame in compositions.

### Activity: Read and Study

:::: {.learning-activity}

Read and study Chapter 3. Be sure to study each of the images provided in this section and how the elements are used. This will increase your understanding of how they function in visual compositions. Before exploring the rest of this chapter, study this essay to help guide you during the process we are exploring: [11 Thoughts: An Introduction to Photographic Composition](https://www.bhphotovideo.com/explora/photography/tips-and-solutions/11-thoughts-introduction-photographic-composition){target="_blank"}, by Todd Vorenkamp [-@11ThoughtsIntroduction].

::: note

***Helpful Hint:*** New York-based B and H Photo is a great resource for buying and learning about photographic and film and video gear.
:::

**Question to Consider**

- Based on your study of this section, what are some observations you can share in your journal and with you facilitator and classmates?

::::

### Activity: Readings on Techniques and Principles of Composition

::: {.learning-activity}

<!-- Read the article [28 Composition Techniques That Will Improve Your Photos](https://petapixel.com/photography-composition-techniques/){target="_blank"}, and [Principles of Design](https://www.getty.edu/education/teachers/building_lessons/principles_design.pdf){target="_blank"}. Practice and apply techniques and principles of design. -->

- Study these helpful resources: [*28 Composition Techniques That Will Improve Your Photos*](https://petapixel.com/photography-composition-techniques/){target="_blank"} [@Carroll28CompositionTechniques2023], and [*Principles of Design*](https://www.getty.edu/education/teachers/building_lessons/principles_design.pdf){target="_blank"} [@Principlesofdesign].  

- Read the next section of Chapter 3, Principles of Composition, and see if you have a richer understanding of composition. Log your observations in your journal.

- Find an example of the use of frame-within-a-frame and triangular composition and share them with your facilitator and classmates.  

:::

## Photographic Themes

The subjects of a visual image includes the objects, people, or items in the frame. E.g., a mountainous landscape, a portrait of twins, etc.

A more advanced approach to composition involves the use of creating a theme or deeper meaning to a composition, or where you take a topic such as clothes on clotheslines and photograph a series of images that reveal their beauty or what they say about the culture, people, or environment where they were shot.

As you grow in your composition skills you will discover how to add more depth, interest, and meaning to your photographs and images.

### Activity: Read and Explore

::: {.learning-activity}

You do not have to create a theme for your photographs in this unit. However, studying websites like the following can help enrich your understanding and find images that stand out in intriguing, startling, fascinating, and emotionally moving ways.

- [Walker Evans MoMA Exhibit](https://www.moma.org/artists/1777){target="_blank"} [-@WalkerEvansMoMA]
- The outstanding Depression Era works of Dorothea Lange are also rich with theme. See [The History Place Dorothea Lange](http://www.historyplace.com/unitedstates/lange/){target="_blank"} [-@HistoryPlaceDorothea]
- [Top 10 Most Famous Portrait Photographers In The World](https://www.boredpanda.com/top-10-photographers-for-travel-portraits/?utm_source=google&utm_medium=organic&utm_campaign=organic){target="_blank"} [-@FamousPhotographersPose2015]

::: note

***Helpful Hint:*** *The photographs of Walker Evans and Dorethea Lange cited above are almost one-hundred years old. But they reveal the way their heartfelt themes and beauty are universal and timeless—the goal of excellent photos.*

:::

Log in your journal and share with a peer in your course what you learned about photographic themes.

:::

## Summary {.unnumbered}

In this unit, you learned about the use of elements, principles, and theme in visual composition and photographic design.

Composition and subject matter are different but intimately related. We can have a simple subject with little composition. A white ball on a black table. Or we can have a complex composition with little subject matter. The bokeh (blurred or out of focus) of rain splashes on a glass window.

We have emphasized composition here because well composed shots are a foundational building block of a good film. As you will learn, if the head space of your shots is too much or too little, or there is a lack of balance of how people are arranged, or if you do not give enough leading entry space in a jogging shot, it will detract from the effect of your film. (There are exceptions to these rules which will be addressed later.) Too many flaws will mark you as an untrained or sloppy filmmaker - something we want to avoid.

::: {.check}

Before you move on to the next unit, you may want to check to make sure that you are able to:

- Describe the elements used in visual compositions.
- Define composition principles.
- Study the works of noted photographers and apply composition elements and principles to photographs you create.
- Create photographs that reveal your understanding of the chapter’s content.

:::

<!-- #### Grading Criteria See the Assessments section for more details on your composition, as well as the grading criteria. Note that entries are expected for every unit. Your journal reflections are submitted at the end of the course as part of the Final Exam: Self Assessment worth 30% of your course grade. -->

## References {.unnumbered}


